<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class UsersTableSeeder extends Seeder

{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('users')->insert([
        [
            'name'=>'John' ,
            'phone'=>'95232645',
            'email'=>'john@gmail.com',
            'password'=>bcrypt('John12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'1',
            'adresse'=>'vedoko',
        ],
        [
            'name'=>'Fabrice', 
            'phone'=>'58624852',
            'email'=>'fabrice@gmail.com',
            'password'=>bcrypt('Fabrice12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'1',
            'adresse'=>'vedoko',
          ],
          [
            'name'=>'Junior',
            'phone'=>'97856234',
            'email'=>'junior@gmail.com',
            'password'=>bcrypt('Junior12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'1',
            'adresse'=>'menontin',
          ],
          [
            'name'=>'Moussa', 
            'phone'=>'56824987',
            'email'=>'moussa@gmail.com',
            'password'=>bcrypt('Moussa12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'4',
            'adresse'=>'guema',
          ],
          [
            'name'=>'Gloria', 
            'phone'=>'98562477',
            'email'=>'gloria@gmail.com',
            'password'=>bcrypt('Gloria12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Feminin',
            'ville_id'=>'1',
            'adresse'=>'agla',
          ],
          [
            'name'=>'Sandrine', 
            'phone'=>'58246352',
            'email'=>'sandrine@gmail.com',
            'password'=>bcrypt('Sandrine12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Feminin',
            'ville_id'=>'1',
            'adresse'=>'zogbo',
          ],
          [
            'name'=>'Ulrich', 
            'phone'=>'56235842',
            'email'=>'ulrich@gmail.com',
            'password'=>bcrypt('Ulriche12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'2',
            'adresse'=>'cocotomey',
          ],
          [
            'name'=>'Claudine',
            'phone'=>'58264715',
            'email'=>'claudine@gmail.com',
            'password'=>bcrypt('Claudine'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Feminin',
            'ville_id'=>'2',
            'adresse'=>'cocotomey',
          ],
          [
            'name'=>'Koffi',
            'phone'=>'94526585',
            'email'=>'koffi@gmail.com',
            'password'=>bcrypt('Koffi12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Masculin',
            'ville_id'=>'2',
            'adresse'=>'godomey',
          ],
          [
            'name'=>'Justine', 
            'phone'=>'65258968',
            'email'=>'justine@gmail.com',
            'password'=>bcrypt('Justine12'),
            'role_id'=>'3',
            'profil'=>'user.jpg',
            'sexe'=>'Feminin',
            'ville_id'=>'2',
            'adresse'=>'calavi',
          ],          
       ]);
    }
}

